% parsePosture.m: Matlab code to parse posture file generated by posture
% Author: Nishanth Koganti
% Date: 2015/09/19

% TODO:
% 1) Implement in python

function [Head,Data] = parsePosture(fileName)

fid = fopen(fileName);

% Ignoring other info
fgets(fid);
fgets(fid);

% Getting the header
Head = strsplit(fgets(fid),',');

% Getting the data
Data = [];
while ~feof(fid)
    line = fgets(fid);
    dat = str2num(line);
    Data = [Data; dat];
end
Data(3,3) = Data(3,3) - 400.0;
Data = Data./1000.0;

fclose(fid);